<?php
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//                         XOOPS XmlWeather Module 1.5	    	 	 //
//                    Just enjoy! Internet for everyone!!			 //
//                      wanikoo <http://www.wanisys.net/>                    //
//  ------------------------------------------------------------------------ //
//                         Based on Weather on your site(weather_xml.php)                       //
//                     	 ( http://notonebit.com/ )		                          //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //
// Author: Kazumi Ono (AKA onokazu)                                          //
// URL: http://www.myweb.ne.jp/, http://www.xoops.org/, http://jp.xoops.org/ //
// Project: The XOOPS Project                                                //
// ------------------------------------------------------------------------- //


if( ! defined( 'XOOPS_ROOT_PATH' ) ) exit ;
$mydirname = basename( dirname( __FILE__ ) ) ;

$modversion['name'] = _MI_XMLWEATHER_NAME;
$modversion['dirname'] = $mydirname;
$modversion['version'] = 1.5;
$modversion['description'] = _MI_XMLWEATHER_DESC;
$modversion['author'] = "docs/credits.txt";
$modversion['credits'] = "docs/credits.txt";
$modversion['help'] = "docs/install.txt";
$modversion['license'] = "docs/credits.txt";
$modversion['official'] = 1;
$modversion['image'] = "images/logo.gif";

//Admin things
$modversion['hasAdmin'] = 0;
$modversion['hasMain'] = 1;

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file
$modversion['tables'][0] = "weather_xml";

// Templates
$modversion['templates'][1]['file'] = 'xmlweather_index.html';
$modversion['templates'][1]['description'] = '';

// Blocks
$modversion['blocks'][1]['file'] = "xmlweather_block.php";
$modversion['blocks'][1]['name'] = _MI_XMLWEATHER_BNAME1;
$modversion['blocks'][1]['description'] = _MI_XMLWEATHER_BDESC1;
$modversion['blocks'][1]['show_func'] = "b_xmlweather_search_show";
$modversion['blocks'][1]['template'] = 'xmlweather_block_search.html';

?>